var mobile_toggle='closed';var map=null;var mapContact=null;function initialize(contenedorMapa,Lat,Lng,map){var latlng=new google.maps.LatLng(Lat,Lng);var myOptions={zoom:18,center:latlng,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:true,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.DROPDOWN_MENU}};map=new google.maps.Map(document.getElementById(contenedorMapa),myOptions);var contentString='<div class="gmap-content"><h2>San Antón Hotel</h2><p>Paseo de Eriste<br /> 22440 Benasque</p></div>';var infowindow=new google.maps.InfoWindow({content:contentString});var marker=new google.maps.Marker({position:latlng,map:map});google.maps.event.addListener(marker,'click',function(){infowindow.open(map,marker);});}
function refrescarCaptcha(){document.getElementById("imageCaptcha").src="classes/secureimage/securimage_show.php?sid="+Math.random();document.getElementById("txtCaptcha").value="";}
function inicializarScriptsBasicos(){var i='';$('.rooms-wrapper div[class^="room-"]:not(div.room-0)').hide();$('#book_room').change(function(e){$('.rooms-wrapper div[class^="room-"]').hide();e.preventDefault();var selectedVal=$(this).val();if(selectedVal>1){for(i=1;i<=selectedVal;i++){$('div[class^=room-'+i+']').show();}}
	else{$('div.room-0').show();}});$('.arrowup img').click(function(){centrarPantallaElemento("body");});if(navigator.userAgent.indexOf("AdobeAIR")<0){if(getCookie('msg')){}else{jQuery(".container-msg-cookie").show();}}
$("#hide-msg-cookie").click(function(){$(".container-msg-cookie").hide();setCookie('msg','hide');});}
function centrarPantallaElemento(elemento){$("html, body").animate({scrollTop:$(elemento).offset().top},1000);}
function setCookie(nombre,valor){var dominio=window.location.hostname;var arr_dominio=dominio.split(".");while(arr_dominio.length>2){arr_dominio.shift();}
var dominio_principal=arr_dominio.join(".");var expiration=(new Date(2037,12,31)).toGMTString();var thecookie=nombre+" = "+escape(valor)+"; expires="+expiration+"; path=/; domain=."+dominio_principal;document.cookie=thecookie;}
function getCookie(nombre){var nombreCookie,valorCookie,cookie=null,cookies=document.cookie.split(';');for(i=0;i<cookies.length;i++){valorCookie=cookies[i].substr(cookies[i].indexOf('=')+1);nombreCookie=cookies[i].substr(0,cookies[i].indexOf('=')).replace(/^\s+|\s+$/g,'');if(nombreCookie==nombre)
cookie=unescape(valorCookie);}
return cookie;}